### PR TITLE
feat(NS-17): display menu items

### PR DESCRIPTION
**Pull request by Zako563**
https://champlainsaintlambert.atlassian.net/browse/NS-17

Implemented the feature to get all menu. Front end and back end:

1. Created the menu entity
2.  the getall  method in the service and controller. 
3. Made the test.
4.   Implemented the front end
5. Implemented Axios Instance

image

### CODE REVIEW

**Review by kyrusho — COMMENTED** [review]
Could you please correct the pr naming please

**Review by kyrusho — APPROVED** [review]
Great work

**Review by Sunveerg — APPROVED** [review]
Maybe change how the available and not available looks otherwise looks good.

**Comment by Zako563** [comment]
> Maybe change how the available and not available looks otherwise looks good.
Ye I was not sure how to do it because it was not in the figma.

**Pull request merged**
